module PayPal
  module AdaptivePayments
  end
end

require "paypal/adaptive_payments/api"
require "paypal/adaptive_payments/response"
require "paypal/adaptive_payments/request"
require "paypal/adaptive_payments/base"
require "paypal/adaptive_payments/payment_info"
require "paypal/adaptive_payments/payment_info_list"
require "paypal/adaptive_payments/funding_type_info"
require "paypal/adaptive_payments/funding_type_list"
require "paypal/adaptive_payments/funding_constraint"
require "paypal/adaptive_payments/sender_identifier"
require "paypal/adaptive_payments/payment"
require "paypal/adaptive_payments/invoice_data"
require "paypal/adaptive_payments/invoice_item"
require "paypal/adaptive_payments/display_options"
require "paypal/adaptive_payments/sender_options"
require "paypal/adaptive_payments/receiver_options"
require "paypal/adaptive_payments/initiating_entity"
require "paypal/adaptive_payments/institution_customer"
require "paypal/adaptive_payments/payment_options"
require "paypal/adaptive_payments/receiver_list"
require "paypal/adaptive_payments/receiver"
require "paypal/adaptive_payments/phone"
require "paypal/adaptive_payments/preapproval"
require "paypal/adaptive_payments/client_details"
require "paypal/adaptive_payments/response/details"
require "paypal/adaptive_payments/response/pay_options"